# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.${DOMAIN}.com:
ORGS_AND_PEERS_VOLUMES

networks:
  byfn:
services:
CERTS_AUTH_ORGS

  orderer.${DOMAIN}.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.${DOMAIN}.com
    container_name: orderer.${DOMAIN}.com
    networks:
      - byfn

ORGS_AND_PEERS_SERVICES
