# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Org${ORG}
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org${ORG}MSP

        # ID to load the MSP definition as
        ID: Org${ORG}MSP

        MSPDir: crypto-config/peerOrganizations/org${ORG}.${DOMAIN}.com/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org${ORG}MSP.admin', 'Org${ORG}MSP.peer', 'Org${ORG}MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org${ORG}MSP.admin', 'Org${ORG}MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org${ORG}MSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.org${ORG}.${DOMAIN}.com
              Port: ${PORT}

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org${ORG}MSP.admin', 'Org${ORG}MSP.peer', 'Org${ORG}MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org${ORG}MSP.admin', 'Org${ORG}MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org${ORG}MSP.admin')"    
            Endorsement:
                Type: Signature
                Rule: "OR('Org${ORG}MSP.peer')"  
